# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Build JS
        run: npm run build --if-present
      - uses: neofinancial/mongo-memory-server-action@v1.0.2
        with:
          db-connection-env-var: MONGODB_CONNECTION_STRING
          run-command: npm test
          binary-version: 4.4.6
          instance-dbName: validation
          instance-port: 27017
          instance-storageEngine: wiredTiger
          mongoms-debug: 1
          
      # - name: Run Jest Tests
      #   run: npm test
